name: Deploy Client - AWS

on:
  workflow_dispatch:
    inputs:
      client:
        description: "Select Client"
        required: true
        type: choice
        options:
          - kmjl
          - candere
          - pml

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLIENT: ${{ github.event.inputs.client }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Build Client
        run: CLIENT=$CLIENT npm run build

      - name: Log
        run: echo "Deploying for $CLIENT"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: react-build-${{ env.CLIENT }}
          path: build

      - name: Deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/react/${{ env.CLIENT }}"
